# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
before_script:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then export JULIA_LOAD_PATH=$JULIA_LOAD_PATH:~/.julia/v0.5/QMC; fi
  - if [ $TRAVIS_JULIA_VERSION = "0.4" ]; then export JULIA_LOAD_PATH=$JULIA_LOAD_PATH:~/.julia/v$TRAVIS_JULIA_VERSION/QMC; fi
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("QMC"); Pkg.test("QMC"; coverage=true)'
